### ISSUE TITLE
LambdaExecutionRole is too broad

### ISSUE THREAD

**Issue by laurrentt** [alexgibs/cfn_lambda_set_permissions#1]
It would be nice to only specify ([here](https://github.com/alexgibs/cfn_lambda_set_permissions/blob/master/sns_add_permissions.json#L68)) the required actions instead of giving root access to the lambda function.

**Comment by laurrentt** [comment]
It works with only those 2 statements: 

```
"Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:*"
                  ],
                  "Resource": "arn:aws:logs:*:*:*"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:AddPermission"
                  ],
                  "Resource": [
                    "*"
                  ]
                }
              ]
```

**Comment by alexgibs** [comment]
Thanks for the suggestion. I've updated that now to restrict the IAM execution role.

Also, I've added the function code in-line now that it is supported via CloudFormation.
